#include "day2_bank.cpp"
int main(){
    HDFC hd;
    cout<<"\nHDFC bank"<<endl;
    // hd.getName();
    // hd.getEstablishedDate();
    // hd.getBankType();
    // hd.getLoanType();
    // hd.getDocsRequired();
    hd.getInterestRate();
    // hd.getInfo();
    SBI sb;
    cout<<"\nSBI bank"<<endl;
    // sb.getName();
    // sb.getEstablishedDate();
    // sb.getBankType();
    // sb.getLoanType();
    // sb.getDocsRequired();
    sb.getInterestRate();
    // sb.getInfo();
    ICICI ic;
    cout<<"\n ICICI bank"<<endl;
    // ic.getName();
    // ic.getEstablishedDate();
    // ic.getBankType();
    // ic.getLoanType();
    // ic.getDocsRequired();
    ic.getInterestRate();
    // ic.getInfo();
    IOB o;
    cout<<"\nIndian Overseas Bank"<<endl;
    // o.getName();
    // o.getEstablishedDate();
    // o.getBankType();
    // o.getLoanType();
    // o.getDocsRequired();
    o.getInterestRate();
    // o.getInfo();
    compare c;
    c.compareInterestRate(hd,sb,ic,o);
    return 0;
}